apiVersion: v2
name: pagopa-mocker
description: Microservice that permits to dynamically generate mocked responses
type: application
version: 1.20.0
appVersion: 1.1.0-3-soapaction-cache-optimization
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
